services:
  - type: web
    name: ecommerce-wedding-backend
    env: node
    rootDir: .
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18


